{% set name = "jupyter-docx-bundler" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d3e2caa9676b09b15eae4d1788f8af80dc9e2b1d713f4cc0bfa3fb56e415017

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - lxml
    - python
    - notebook >=5.0
    - pypandoc >=1.4
    - nbconvert >=5.5
    - pandas
    - pandoc >=2.7
    - pandocfilters
    - requests
    - tabulate
    - tornado

test:
  imports:
    - jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
  dev_url: https://github.com/m-rossi/jupyter-docx-bundler

extra:
  recipe-maintainers:
    - m-rossi
