{% set name = "jupyter-docx-bundler" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82e15319bcac37ab72e981f410d7ff52cfba9d52df7aa54da747e39a53e0cd3c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - importlib-resources
    - lxml
    - nbconvert >=7.0
    - notebook >=7.0
    - pandas
    - pandoc >=2.11,<3
    - pandocfilters
    - pypandoc >=1.4
    - python >={{ python_min }}
    - requests
    - tabulate

test:
  imports:
    - jupyter_docx_bundler
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
  dev_url: https://github.com/m-rossi/jupyter-docx-bundler

extra:
  recipe-maintainers:
    - m-rossi
