{% set name = "jupyter-docx-bundler" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf3b4fb145d4ffc26c0ebcf67046fab0ceb102ecc8ca3e9e749e257c59791d9f

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - importlib_resources  # [py<39]
    - lxml
    - nbconvert >=7.0
    - notebook >=5.0
    - pandas
    - pandoc >=2.11,<2.20
    - pandocfilters
    - pypandoc >=1.4
    - python
    - requests
    - tabulate
    - tornado

test:
  imports:
    - jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
  dev_url: https://github.com/m-rossi/jupyter-docx-bundler

extra:
  recipe-maintainers:
    - m-rossi
