{% set name = "jupyter-docx-bundler" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2b27e2427a3ac78b9501388cae0f772b23fa55cc553caecf62e12f6dc1b9928

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - python
    - notebook >=5.0
    - pypandoc >=1.4
    - nbconvert >=5.5
    - pandoc >=2.0
    - requests
    - tornado

test:
  imports:
    - jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
  dev_url: https://github.com/m-rossi/jupyter-docx-bundler

extra:
  recipe-maintainers:
    - m-rossi
