{% set name = "jupyter-docx-bundler" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33213a24baf4fe63e0665ddd2ad94e8b8a4701d58dfe23a070d70336304b0cdf

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - importlib_resources  # [py<39]
    - lxml
    - nbconvert >=5.5
    - notebook >=5.0
    - pandas
    - pandoc >=2.11,<2.14
    - pandocfilters
    - pypandoc >=1.4
    - python
    - requests
    - tabulate
    - tornado

test:
  imports:
    - jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
  dev_url: https://github.com/m-rossi/jupyter-docx-bundler

extra:
  recipe-maintainers:
    - m-rossi
