{% set name = "jupyter-docx-bundler" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82e15319bcac37ab72e981f410d7ff52cfba9d52df7aa54da747e39a53e0cd3c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools >=38.6.0
    - setuptools_scm
    - python >=3.8
  run:
    - importlib_resources  # [py<39]
    - lxml
    - nbconvert >=7.0
    - notebook >=5.0
    - pandas
    - pandoc >=2.11,<2.20
    - pandocfilters
    - pypandoc >=1.4
    - python >=3.8
    - requests
    - tabulate
    - tornado

test:
  imports:
    - jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
  dev_url: https://github.com/m-rossi/jupyter-docx-bundler

extra:
  recipe-maintainers:
    - m-rossi
