travis:
  secure:
    BINSTAR_TOKEN: TpvzJ/r7Xo/7G1v/L7yUor2DqmbHScCVcaP3AbfGnBYnJyuLuQT3ieMerPVX8NovOKLKv+mp6Cqdp6sbrx3EtCwtw+PGuPhMPFZnVs0DLna52DNBf3/CdOmUJPLaI180to9ed0MnUHZcKbINVl9HPQEDJ4LstfNcZjb59b+duh+E4zXRX9hC3BFS9+ksAXA1GBPlQHZakvL2SHeEag7tpYDKzFBm9JmX3bDUeuNuI3OJMtNoxbWiUNsfdjdGTH+g9ng2KLMYetHs7e9DssTtvPQyydinB1ReqLm1vOx7JAxtaVdnV3vg1TAR6atEsGCiNgb2eKVd/8h9bmPLVzAm6bg2xqCzD7QAy9bzf0gzH0T5YUc7BHYv08nnFSeRZlho3kivb9am6qHC1if0JzcG9sW8boDFcWcm47oNcZjeUvWymRSvzvz3p27PsHmu9LUxjALfUiNwojGm/3lowlRuKYrWMfWayyjNxDljXSv49NONSZX86cWJfIYUDr/2NghsTlpD5O7rrmS9TmQs0mVm3TQAoNlln2RCft3eqOa4ji4kH0rXdKK/hFs+KjEKkzcp3Sxck0yjFYqai8GC+b6VLV2gXy9z7+VdqQEmSUbQ45VZTOegMsnHeZTQCrQ3Sl9CikdXiyo4FPAhAVqDG8h/Q3tFGmcwfSQtX5nayvNR0Xg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
