travis:
  secure:
    BINSTAR_TOKEN: LYeuKCRozA0k/ddb90ZgGEIlA7Qar2fID5PEYO1w9TyUILK3C6karhmXHi3OSBm9zpLNW91wIvT5YleSa5Px9uZuNKDO+PsvvnZCKJmb2Sy7pgmmVvm9tyLOLJWxk6r9K06hXfc97++hJD+YFcAGz9hSeFGoSToylJonScVH1Ni47kqPICjKCG2t18JN67mi7ay9Ov/FRDSzjDuAi0c6hbUsvh6gf+zmd/Zw9k4z/f97jV8KtkRadGAxX3zDxl+VkoACFIoODP6f/Ni/KgwYP02YkvBI+ivXrpnDqqGI3MEKay3T6FOXfD71kn27dXBeh9wwzF4Haxp1CR1JlfpTBL6edBG8UTGPv9rJ7bbJpHQ9XyMMEzyDlj1/4VK98Q4zTLTEpcqrqCJSODj5GC1UfAB+Z55i6JL6Go/Skn5awRoGTicujapuwSsdrJgi/+EzFu8l8iNzBgw1bH4DKrPFoJfIMNJ2iW1mukeJzeJdBzO1dML8ljIWZV6ciTXUX5F69tHoOTmCgD3Q3pMxTETCEw9X2VLapcnrKUufgBAB4vP6qer4S/Zz/MV0bvTy+5LkmGuob1/i7PfPCXbibuXpz/1CtOtOyXfcbjh1M2/J+WioHn8rmEOnjmr94e7WMmXaX+eppEZ4ASkD9lNYkqksQlH/GEyO0pCRPorwggOf0/o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
